# for shared libraries 
so-y += bbliblogger.o
so-y += bbliblogger_layout.o
so-y += bbliblogger_cmd.o
# for static libraries
obj-y += bbliblogger.o
obj-y += bbliblogger_layout.o
obj-y += bbliblogger_cmd.o
