# for shared libraries 
so-y += bblibos_tsk.o
so-y += bblibos_thr.o
so-y += bblibos_sem.o
so-y += bblibos_mutex.o
so-y += bblibos_event.o
# for static libraries
obj-y += bblibos_tsk.o
obj-y += bblibos_thr.o
obj-y += bblibos_sem.o
obj-y += bblibos_mutex.o
obj-y += bblibos_event.o
