# for shared libraries 
so-y += bblibutils_stack.o
so-y += bblibutils_ringBuffer.o
so-y += bblibutils_que.o
so-y += bblibutils_list.o
so-y += bblibutils_shareMemory.o
# for static libraries
obj-y += bblibutils_stack.o
obj-y += bblibutils_ringBuffer.o
obj-y += bblibutils_que.o
obj-y += bblibutils_list.o
obj-y += bblibutils_shareMemory.o
#
